# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ai_inference.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ai_inference.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x61i_inference.proto\x12\x0c\x61i_inference\" \n\x10SentimentRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"6\n\x11SentimentResponse\x12\r\n\x05label\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x02\"\x1c\n\nLLMRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\"\x1c\n\x0bLLMResponse\x12\r\n\x05token\x18\x01 \x01(\t\"#\n\x12SummarizationChunk\x12\r\n\x05\x63hunk\x18\x01 \x01(\t\"(\n\x15SummarizationResponse\x12\x0f\n\x07summary\x18\x01 \x01(\t\"\x1e\n\x0b\x43hatMessage\x12\x0f\n\x07message\x18\x01 \x01(\t2\xe1\x02\n\x0b\x41IInference\x12T\n\x11SentimentAnalysis\x12\x1e.ai_inference.SentimentRequest\x1a\x1f.ai_inference.SentimentResponse\x12N\n\x15RealTimeLLMGeneration\x12\x18.ai_inference.LLMRequest\x1a\x19.ai_inference.LLMResponse0\x01\x12]\n\x12\x42\x61tchSummarization\x12 .ai_inference.SummarizationChunk\x1a#.ai_inference.SummarizationResponse(\x01\x12M\n\x11LiveChatAssistant\x12\x19.ai_inference.ChatMessage\x1a\x19.ai_inference.ChatMessage(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai_inference_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SENTIMENTREQUEST']._serialized_start=36
  _globals['_SENTIMENTREQUEST']._serialized_end=68
  _globals['_SENTIMENTRESPONSE']._serialized_start=70
  _globals['_SENTIMENTRESPONSE']._serialized_end=124
  _globals['_LLMREQUEST']._serialized_start=126
  _globals['_LLMREQUEST']._serialized_end=154
  _globals['_LLMRESPONSE']._serialized_start=156
  _globals['_LLMRESPONSE']._serialized_end=184
  _globals['_SUMMARIZATIONCHUNK']._serialized_start=186
  _globals['_SUMMARIZATIONCHUNK']._serialized_end=221
  _globals['_SUMMARIZATIONRESPONSE']._serialized_start=223
  _globals['_SUMMARIZATIONRESPONSE']._serialized_end=263
  _globals['_CHATMESSAGE']._serialized_start=265
  _globals['_CHATMESSAGE']._serialized_end=295
  _globals['_AIINFERENCE']._serialized_start=298
  _globals['_AIINFERENCE']._serialized_end=651
# @@protoc_insertion_point(module_scope)
