# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import ai_inference_pb2 as ai__inference__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ai_inference_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AIInferenceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SentimentAnalysis = channel.unary_unary(
                '/ai_inference.AIInference/SentimentAnalysis',
                request_serializer=ai__inference__pb2.SentimentRequest.SerializeToString,
                response_deserializer=ai__inference__pb2.SentimentResponse.FromString,
                _registered_method=True)
        self.RealTimeLLMGeneration = channel.unary_stream(
                '/ai_inference.AIInference/RealTimeLLMGeneration',
                request_serializer=ai__inference__pb2.LLMRequest.SerializeToString,
                response_deserializer=ai__inference__pb2.LLMResponse.FromString,
                _registered_method=True)
        self.BatchSummarization = channel.stream_unary(
                '/ai_inference.AIInference/BatchSummarization',
                request_serializer=ai__inference__pb2.SummarizationChunk.SerializeToString,
                response_deserializer=ai__inference__pb2.SummarizationResponse.FromString,
                _registered_method=True)
        self.LiveChatAssistant = channel.stream_stream(
                '/ai_inference.AIInference/LiveChatAssistant',
                request_serializer=ai__inference__pb2.ChatMessage.SerializeToString,
                response_deserializer=ai__inference__pb2.ChatMessage.FromString,
                _registered_method=True)


class AIInferenceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SentimentAnalysis(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RealTimeLLMGeneration(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchSummarization(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LiveChatAssistant(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AIInferenceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SentimentAnalysis': grpc.unary_unary_rpc_method_handler(
                    servicer.SentimentAnalysis,
                    request_deserializer=ai__inference__pb2.SentimentRequest.FromString,
                    response_serializer=ai__inference__pb2.SentimentResponse.SerializeToString,
            ),
            'RealTimeLLMGeneration': grpc.unary_stream_rpc_method_handler(
                    servicer.RealTimeLLMGeneration,
                    request_deserializer=ai__inference__pb2.LLMRequest.FromString,
                    response_serializer=ai__inference__pb2.LLMResponse.SerializeToString,
            ),
            'BatchSummarization': grpc.stream_unary_rpc_method_handler(
                    servicer.BatchSummarization,
                    request_deserializer=ai__inference__pb2.SummarizationChunk.FromString,
                    response_serializer=ai__inference__pb2.SummarizationResponse.SerializeToString,
            ),
            'LiveChatAssistant': grpc.stream_stream_rpc_method_handler(
                    servicer.LiveChatAssistant,
                    request_deserializer=ai__inference__pb2.ChatMessage.FromString,
                    response_serializer=ai__inference__pb2.ChatMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai_inference.AIInference', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ai_inference.AIInference', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AIInference(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SentimentAnalysis(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai_inference.AIInference/SentimentAnalysis',
            ai__inference__pb2.SentimentRequest.SerializeToString,
            ai__inference__pb2.SentimentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RealTimeLLMGeneration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ai_inference.AIInference/RealTimeLLMGeneration',
            ai__inference__pb2.LLMRequest.SerializeToString,
            ai__inference__pb2.LLMResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchSummarization(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/ai_inference.AIInference/BatchSummarization',
            ai__inference__pb2.SummarizationChunk.SerializeToString,
            ai__inference__pb2.SummarizationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LiveChatAssistant(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/ai_inference.AIInference/LiveChatAssistant',
            ai__inference__pb2.ChatMessage.SerializeToString,
            ai__inference__pb2.ChatMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
