worker_processes auto;

events {
    worker_connections 1024;
}

http {

    upstream grpc_backend {
        server server1:50051;
        server server2:50051;
        server server3:50051;
    }

    server {
        listen 50051 http2;

        location / {
            grpc_pass grpc://grpc_backend;
        }

        error_page 502 = /error502grpc;

        location = /error502grpc {
            internal;
            default_type application/grpc;
            add_header grpc-status 14;
            add_header content-length 0;
            return 204;
        }
    }
}